name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    # define a grid system where each combination runs in parallel. 
    # (ubuntu-latest, 14) (ubuntu-latest, 16) (windows-latest, 14) (windows-latest, 16)
    strategy:
      matrix:
        node-version: [14, 16] # custom name
        operating-system: [ubuntu-latest, windows-latest] # custom name
    runs-on: ${{ matrix.operating-system }} # access via "matrix" context
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # access via "matrix" context
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build